===================================================
Experiment Configuration:
- Hidden Dimension: 736
- Number of Heads: 8
- Number of Blocks: 7
- Patch Size: 16
- Learning Rate: 1e-4
- Start Time: Fri Dec 13 08:01:36 AM EST 2024
===================================================
Starting training for 7 epochs...

Epoch 1/7
Training:   0%|          | 0/781 [00:00<?, ?it/s]Training:   0%|          | 0/781 [00:01<?, ?it/s]
Traceback (most recent call last):
  File "/home/michel/repos/scratch_vit/train_cifar.py", line 295, in <module>
    vit_cifar.train_model()
  File "/home/michel/repos/scratch_vit/train_cifar.py", line 221, in train_model
    train_loss = self.train_iter()
  File "/home/michel/repos/scratch_vit/train_cifar.py", line 165, in train_iter
    self.model.backward(error)
  File "/home/michel/repos/scratch_vit/model/vit_finished.py", line 126, in backward
    error = block.backward(error)
  File "/home/michel/repos/scratch_vit/model/transformer_block.py", line 87, in backward
    grad_in = self.gelu.backward(grad_in)
  File "/home/michel/repos/scratch_vit/model/activations.py", line 95, in backward
    return (grad * (self.cdf + self.x * pdf)).astype(self.x.dtype)
  File "cupy/_core/core.pyx", line 1271, in cupy._core.core._ndarray_base.__add__
  File "cupy/_core/_kernel.pyx", line 1350, in cupy._core._kernel.ufunc.__call__
  File "cupy/_core/_kernel.pyx", line 645, in cupy._core._kernel._get_out_args_from_optionals
  File "cupy/_core/core.pyx", line 2836, in cupy._core.core._ndarray_init
  File "cupy/_core/core.pyx", line 243, in cupy._core.core._ndarray_base._init_fast
  File "cupy/cuda/memory.pyx", line 738, in cupy.cuda.memory.alloc
  File "cupy/cuda/memory.pyx", line 1424, in cupy.cuda.memory.MemoryPool.malloc
  File "cupy/cuda/memory.pyx", line 1445, in cupy.cuda.memory.MemoryPool.malloc
  File "cupy/cuda/memory.pyx", line 1116, in cupy.cuda.memory.SingleDeviceMemoryPool.malloc
  File "cupy/cuda/memory.pyx", line 1137, in cupy.cuda.memory.SingleDeviceMemoryPool._malloc
  File "cupy/cuda/memory.pyx", line 1382, in cupy.cuda.memory.SingleDeviceMemoryPool._try_malloc
  File "cupy/cuda/memory.pyx", line 1385, in cupy.cuda.memory.SingleDeviceMemoryPool._try_malloc
cupy.cuda.memory.OutOfMemoryError: Out of memory allocating 387,383,296 bytes (allocated so far: 24,178,298,880 bytes).

real	0m2.904s
user	0m3.437s
sys	0m0.638s
