===================================================
Experiment Configuration:
- Hidden Dimension: 576
- Number of Heads: 6
- Number of Blocks: 12
- Patch Size: 16
- Learning Rate: 1e-5
- Start Time: Fri Dec 13 11:07:30 AM EST 2024
===================================================
Starting training for 7 epochs...

Epoch 1/7
Training:   0%|          | 0/781 [00:00<?, ?it/s]Training:   0%|          | 0/781 [00:01<?, ?it/s]
Traceback (most recent call last):
  File "/home/michel/repos/scratch_vit/train_cifar.py", line 295, in <module>
    vit_cifar.train_model()
  File "/home/michel/repos/scratch_vit/train_cifar.py", line 221, in train_model
    train_loss = self.train_iter()
  File "/home/michel/repos/scratch_vit/train_cifar.py", line 162, in train_iter
    y_pred = self.model.forward(x)
  File "/home/michel/repos/scratch_vit/model/vit_finished.py", line 96, in forward
    out = block.forward(out)
  File "/home/michel/repos/scratch_vit/model/transformer_block.py", line 58, in forward
    out = self.gelu(out)
  File "/home/michel/repos/scratch_vit/model/activations.py", line 98, in __call__
    return self.forward(x)
  File "/home/michel/repos/scratch_vit/model/activations.py", line 88, in forward
    self.cdf = 0.5 * (1 + cupyx.scipy.special.erf(x / cp.sqrt(2)))
  File "cupy/_core/_kernel.pyx", line 1350, in cupy._core._kernel.ufunc.__call__
  File "cupy/_core/_kernel.pyx", line 645, in cupy._core._kernel._get_out_args_from_optionals
  File "cupy/_core/core.pyx", line 2836, in cupy._core.core._ndarray_init
  File "cupy/_core/core.pyx", line 243, in cupy._core.core._ndarray_base._init_fast
  File "cupy/cuda/memory.pyx", line 738, in cupy.cuda.memory.alloc
  File "cupy/cuda/memory.pyx", line 1424, in cupy.cuda.memory.MemoryPool.malloc
  File "cupy/cuda/memory.pyx", line 1445, in cupy.cuda.memory.MemoryPool.malloc
  File "cupy/cuda/memory.pyx", line 1116, in cupy.cuda.memory.SingleDeviceMemoryPool.malloc
  File "cupy/cuda/memory.pyx", line 1137, in cupy.cuda.memory.SingleDeviceMemoryPool._malloc
  File "cupy/cuda/memory.pyx", line 1382, in cupy.cuda.memory.SingleDeviceMemoryPool._try_malloc
  File "cupy/cuda/memory.pyx", line 1385, in cupy.cuda.memory.SingleDeviceMemoryPool._try_malloc
cupy.cuda.memory.OutOfMemoryError: Out of memory allocating 303,169,536 bytes (allocated so far: 24,034,792,960 bytes).

real	0m2.689s
user	0m3.119s
sys	0m0.688s
